# Generated by Django 3.1 on 2020-08-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='identifier',
            new_name='ssn',
        ),
    ]
