# Generated by Django 3.1 on 2020-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientportal", "0002_auto_20200816_0343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AddField(
            model_name="patient",
            name="opendental_patient_id",
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
