# Copyright (c) 2020 Ethan Nguyen. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1 on 2020-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientportal", "0002_auto_20200816_0343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AddField(
            model_name="patient",
            name="opendental_patient_id",
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
